baseURL = "http://imadali.net"
languageCode = "en-us"
title = "Imad Ali"
theme = "hello-friend-ng"

[params]

  disableReadOtherPosts = true

  dateformNumTime = "2006-01-02"

  [[params.social]]
    name = "email"
    url  = "mailto:imadmali@gmail.com"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/imadali"

  [[params.social]]
    name = "github"
    url  = "https://github.com/imadmali"

  [[params.social]]
    name = "linkedin"
    url  = "https://linkedin.com/in/imadmali"

  [params.logo]
    logoText = "imad ali"
    logoCursorDisabled = true

[author]
  name = "Imad Ali"

[menu]

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"
