# Site settings
# title: Solo, a Jekyll Theme
# tag_text: Solo
# description: Solo is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s # responsive.

repository: imadmali.github.io
# Build settings
gems: ['jekyll-github-metadata']
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
